spring:
  application:
    name: otus-sotset

  master-datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/sotset
    username: postgres
    password: password
    platform: postgresql
    maximum-pool-size: 90

  slave-datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/sotset
    username: postgres
    password: password
    platform: postgresql
    maximum-pool-size: 90

  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

server:
  port: 8080

otus-sotset:
  auth:
    jwt:
      secret: "*****"
      issuer: "otus-sotset"
      token-ttl-seconds: 3600
