spring:
  application:
    name: otus-sotset

  datasource:
    url: jdbc:mysql://localhost:3306/sotset
    username: root
    password: password
    hikari:
      maximum-pool-size: 150

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

server:
  port: 8080
