version: '3.1'
name: otus-sotset
services:

  app:
    build: ..
    ports:
      - "8080:8080"
    volumes:
      - ..:/code
    depends_on:
      - postgres-master
      - postgres-slave-1
    environment:
      - SPRING_MASTER_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-master:5432/sotset
      - SPRING_SLAVE_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-slave-1:5432/sotset

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sotset
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  postgres-master:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sotset
    command: |
      postgres 
      -c wal_level=replica 
      -c max_wal_senders=10 
      -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/master_pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/db-init:/docker-entrypoint-initdb.d/

  postgres-slave-1:
    image: postgres
    restart: unless-stopped
    user: postgres
    depends_on:
      - postgres-master
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      pg_basebackup --pgdata=/var/lib/postgresql/data -R --host=postgres-master --port=5432 --no-password
      chmod 0700 /var/lib/postgresql/data
      postgres -c cluster_name=pgslave1
      "
    ports:
      - "5433:5432"

  postgres-slave-2:
    image: postgres
    restart: unless-stopped
    user: postgres
    depends_on:
      - postgres-master
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      pg_basebackup --pgdata=/var/lib/postgresql/data -R --host=postgres-master --port=5432 --no-password
      chmod 0700 /var/lib/postgresql/data
      postgres -c cluster_name=pgslave2
      "
    ports:
      - "5434:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
